# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configuration globale
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_check_update = false

  # Bastion - Point d'entrée pour la gestion
  config.vm.define "bastion" do |bastion|
    bastion.vm.hostname = "k3s-bastion"
    bastion.vm.network "private_network", ip: "192.168.56.10"
    
    bastion.vm.provider "virtualbox" do |vb|
      vb.name = "k3s-bastion"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # Master - K3s Server
  config.vm.define "master" do |master|
    master.vm.hostname = "k3s-master"
    master.vm.network "private_network", ip: "192.168.56.11"
    
    master.vm.provider "virtualbox" do |vb|
      vb.name = "k3s-master"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Worker 1
  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "k3s-worker-1"
    worker.vm.network "private_network", ip: "192.168.56.12"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "k3s-worker-1"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Worker 2
  config.vm.define "worker2" do |worker|
    worker.vm.hostname = "k3s-worker-2"
    worker.vm.network "private_network", ip: "192.168.56.13"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "k3s-worker-2"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Générer l'inventaire Ansible après la création des VMs
  config.vm.provision "shell", run: "always" do |s|
    s.inline = <<-SHELL
      # Ce script s'exécute sur chaque VM pour collecter les IPs
      # L'inventaire sera généré manuellement ou via un script externe
      echo "VM provisioned: $(hostname) - IP: $(ip -4 addr show eth1 | grep -oP '(?<=inet\\s)\\d+(\\.\\d+){3}')"
    SHELL
  end
end
